### PR TITLE
Support PEP 561 by add a py.typed file

### PR DESCRIPTION
**Pull request by 0xTowel**
Per PEP 561, "Package maintainers who wish to support type checking of their code MUST add a marker file named py.typed to their package supporting typing."

### CODE REVIEW

**Comment by lunixbochs** [comment]
This is useless unless I have a setup.py / upload this to pypi right?

**Comment by 0xTowel** [comment]
MyPy won't try to typehint 3rd party libraries if it doesn't detect they are type hinted. It detects if they are inline type hinted via the `py.typed` file existence.

**Comment by lunixbochs** [comment]
yeah, I gathered that, but this can't currently be installed as a third party library in any meaningful way as it's just a single python file with no packaging metadata

**Comment by 0xTowel** [comment]
If you're not looking to move this to a package in the future then you're right it's probably not helpful. Closing.

**Comment by lunixbochs** [comment]
I might upload to pypi at some point, but half the point of mpwn for me is the single portable file aspect so packaging it isn’t the biggest priority. When I get around to packaging it I’ll include this, and thank you, because I didn’t know about py.typed.

**Comment by 0xTowel** [comment]
If you do decide to make the move to packaging this, you could look at [bottle ](https://github.com/bottlepy/bottle) for some inspiration.

It is a micro web-framework, and, similar to you, the entire thing is contained in a single file (but it is also packaged!). Might have some ideas in there that suit your situation.

Thanks for this project -- it's nice to see fun, usable, modern tools written like this.

**Pull request closed without merging**
